version: '3.9'
services:
    postgres:
        image: postgres:17
        container_name: postgres_container
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2gb
